### ISSUE TITLE
should `(x, 1) = (4, 1)` work?

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#11]
I was trying out what the tuitoral called tuple pattern-matching,
trying to see if it was just what
Javascript, and Julia and Python, etc call _destructuring_.

```
>=> (x,y)=(1, 2.0)

>=> x
1
>=> y
2.0
>=> (a,(b,c))=(1, (2.0, 3))

>=> a
1
>=> b
2.0
>=> c
3
>=> (z,1)=(10, 1)
Parse error:1:6:
  |
1 | (z,1)=(10, 1)
  |      ^^
unexpected "=("
expecting "#deriv", "- ", "::", '$', '*', '+', '.', '/', '<', '>', '^', end of input, end of line, or term
```

I thought `(z,1)=(10, 1)` might work, but it did not parse.

It would work with tuple-pattern matching in F#
[see docs](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching#tuple-pattern)

I am not sure if either that should be fixed,
or if the tutorial should just be amended to say _destructuring_

**Comment by dougalm** [comment]
Yes, patterns are currently quite limited: they can only be variable names or tuples of patterns. I agree that "destructuring" might be a more appropriate term than "pattern matching". I'll add a note to the tutorial program.

I'd like this to change. Pattern-matching against the constructors of an ADT is part of what makes functional programming so much fun. But Dex doesn't even have sum types yet. (Except to the extent that you can treat literal integers as an infinite sum ` ...| -1 | 0 | 1 | ..`, which is why you understandably expected `(x,1)=(0,1)` to work).

Sum types are planned, but probably not for a while. As important as they are, I think they're less necessary for numerical programming. Autodiff, GPU/TPU backends and typeclasses are higher on the agenda.

**Comment by kthielen** [comment]
It's problematic to accept refutable pattern matching outside of some bounded context.  For example, in a list/array comprehension it's easy to interpret a refutable pattern as a filter condition (if the value doesn't match, it's not part of the result).  But for a local variable binding in a function, what does it mean if a refutable pattern match fails?  If you have a bias for total functions then you might prefer not to have to answer that question, so only accept irrefutable patterns for local variable introduction.

I have a somewhat similar project (https://github.com/Morgan-Stanley/hobbes), and I took that approach to just accept irrefutable patterns for variable binding in functions, but refutable patterns in array comprehensions as filter conditions.  I have a requirement for exhaustiveness and reachability in pattern match tables for basically the same reasons (otherwise you have to throw exceptions on unmatched inputs or implicitly wrap the whole state in a "maybe" or blah blah blah).

Anyway, different people prefer different approaches but IMHO only accepting irrefutable patterns for top-level bindings here is a reasonable principled choice for Dex to make.

**Comment by dougalm** [comment]
Thanks @kthielen, well put. Even if/when we add refutable patterns for case expressions and filters on index comprehensions, we'll still probably stick with irrefutable patterns for let and lambda binders.
