### ISSUE TITLE
repeated inlinings?

### ISSUE THREAD

**Issue by jyh1** [google-research/dex-lang#13]
In the `simplify` pass, it seems the rhs of the definition will be processed at every occurrence site? For example:

```
:simp (arr = for i::2 . 0; (arr, arr))
(tab::2=>Int = (for  i::2 . 
    0);
(tab_1::2=>Int = (for  i::2 . 
    0);
(tab, tab_1)))
```

Instead of creating one array, the program ends up constructing two after simplify pass? This will also cause exponential inlinings?

```
:simp (arr = (arr2 = for i::2 . 1; (arr2, arr2)); (arr, arr))
(tab::2=>Int = (for  i::2 . 
    1);
(tab_1::2=>Int = (for  i::2 . 
    1);
(tab_2::2=>Int = (for  i::2 . 
    1);
(tab_3::2=>Int = (for  i::2 . 
    1);
(tab, tab_1, tab_2, tab_3)))))
```

**Comment by dougalm** [comment]
Yes, that's right. But the array is only inlined because it's considered atomic (it's just a repeated constant) and isn't expected to incur any runtime cost. For example, consider what happens if building the array actually involves some work:

    :simp (arr = (arr2 = for i::2 . 1.0 + 2.0; (arr2, arr2)); (arr, arr))
    (arr::2=>Real = (arr2::2=>Real = (for  i::2 . 
                        (%fadd(1.0, 2.0)));
                    arr2);
    (arr, arr, arr, arr))

(Actually, this array could be considered trivial too if we hoisted the expression `1.0 + 2.0`, but the compiler doesn't know how to hoist free subexpressions yet.)

These atomic arrays are expressed using the [`NAtomicFor`](https://github.com/google-research/dex-lang/blob/master/src/lib/Syntax.hs#L211) construct you were finding bugs in earlier. It lets us represent an array that can be trivially constructed from existing arrays without actually materializing it. For example, if we transpose an array twice, we get back the original array, rather than materializing the transposed array and a copy of the original array:

    :normalized ..
      x = [[1,2],[3,4],[5,6]]
      xt.i.j = x.j.i
      xtt.i.j = xt.j.i
      xtt
    (x::3=>2=>Int = [[1, 2], [3, 4], [5, 6]];
    (xt::2=>3=>Int = (for  i::2 . 
        (for  j::3 . 
            x.j.i));
    (xtt::3=>2=>Int = (for  i::3 . 
        (for  j::2 . 
            xt.j.i));
    xtt)))

    :simp ..
      x = [[1,2],[3,4],[5,6]]
      xt.i.j = x.j.i
      xtt.i.j = xt.j.i
      xtt
    (x::3=>2=>Int = [[1, 2], [3, 4], [5, 6]];
    x)

**Comment by jyh1** [comment]
Makes sense! Thanks for the clarification.
