### ISSUE TITLE
linearize errors with CompilerBug

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#17]
For example:
```
>=> f :: Real -> Real
... f x = 2.0 * x

>=> f 2.4
4.8
>=> linearize f
Compiler bug!Can't lower type to imp: (Real -> (Real, (Real -> Real)))
CallStack (from HasCallStack):
  error, called at src/lib/Imp.hs:121:8 in dex-0.1.0.0-EI9xXWhSqyj2zqWgzLwNt8:Imp
>=>
```

I believe this is as mentioned in the Prelude:
> Vector spaces and automatic differentiation. Note that many of the following have implicit vector space typeclass constraints. For now these are not checked by the type checker.

But I figure I open an issue track, and so this is googleable by anyone running into this later

**Comment by oxinabox** [comment]
Maybe this is not a vector space thing,
since i get it on real vectors too 

```
>=> h :: (2=>Real) -> (2=>Real)
... h x = x

>=> h [1.0, 2.0]
[1.0, 2.0]
>=> linearize h
Compiler bug!Can't lower type to imp: (2=>Real -> (2=>Real, (2=>Real -> 2=>Real)))
CallStack (from HasCallStack):
  error, called at src/lib/Imp.hs:121:8 in dex-0.1.0.0-EI9xXWhSqyj2zqWgzLwNt8:Imp
```

**Comment by dougalm** [comment]
Thanks for these bug reports! What you're seeing here is actually my helpful error message for "I don't know how to print a function". a583e03e3b tries to improve that. You should now see the following:

    f :: Real -> Real
    f x = 2.0 * x

    :p linearize f 2.4
    > Type error: Can't print values of type: (Real, (Real --o Real))

Should we be able to print functions? It'd be nice! I'm guessing you were trying to inspect the linearized function. Inspecting the IRs with `:normalized`, `:simp` etc will be another way to inspect the result of differentiation once AD works.

I'm currently implementing AD but it's still early. In the interpreter, linearize and transpose work for simple scalar functions, but they don't even handle reductions or higher order derivatives. So you can try your example (fully applied) using `dex --interp repl`:

    f :: Real -> Real
    f x = 2.0 * x

    :p (y, linfun) = linearize f 2.4
       (y, linfun 10.0)
    > (4.8, 20.0)

But the interpreter is just a simple (and very slow) reference implementation. In the *compiler*, AD isn't implemented at all. I've only gotten as far as deleting the old implemenation... If you run the above with the compiler backend, `dex repl`, you ought to get a "not implemented" error but actually you get a much more confusing error. Rather than fixing the error message, I'm just going to go ahead and start implementing AD in the compiler :).

**Comment by oxinabox** [comment]
> Should we be able to print functions? It'd be nice! I'm guessing you were trying to inspect the linearized function

I expected to see:
```
 (<<λ>>) :: (Real, (Real --o Real))
```
or something like that.
Telling me I had gotten back a function
