### ISSUE TITLE
Add support for table literals of functions

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#177]
I think this might be a known issue, but
```[\p:(Real=>Real). p]```
gives
```
Compiler bug!
Please report this at github.com/google-research/dex-lang/issues

shouldn't appear after Simp: ((Real => Real) -> Real => Real)
Checking IR variant
Checking module:
Module (Simp)
  unevaluated decls:
  tmp:((Fin 1) => (Real => Real) -> Real => Real) =
    %OpExpr (TabCon () [()])
      ((Fin 1) => (Real => Real) -> Real => Real)
      (\p:(Real => Real).  p)
  
  evaluated bindings:
  (_ans_ @> (((Fin 1) => (Real => Real) -> Real => Real), tmp))
```

**Comment by dougalm** [comment]
Yes, that's a known issue (c.f. #27). But now that we have ADTs, we should be able to fix it! The problem is that we don't have any runtime representation for functions. We inline and beta-reduce them all at compile time. But we don't know a function's definition statically if it's pulled out of a table with a runtime index (or, similarly, if it's produced by a case expression) so we can't inline it. At one point we had a `Data` typeclass-like constraint on table constructors to rule out table-literals-of-functions. But with case expressions and ADTs, we should be able to just defunctionalize through them, carrying a case expression on a synthesized ADT (representing the lexical environment of each possible function) to its eventual use site. We need to do the same thing for AD through case expressions anyway (because you produce a different linearized function for each branch, which is similar) so this is on the critical path. But it's still a few weeks away.

**Comment by duvenaud** [comment]
Ah, thanks for explaining.  So a lookup on a table of functions will essentially become a big function with a ```case``` switching on the index looked up, is that right?

**Comment by dougalm** [comment]
Yes, something like that. The case switching on the index looked up will actually be at the call site(s), whereas the table itself will be a pure-data table containing the original function's environments. Here's an example. If we started with a program like this:

```
y = 2
z = (3, 4.5)
functionTable : Fin 3 => (Int -> Int) = [\x:Int. x + x, \x:Int. x + y, \x:Int. x * fst z]
i = ...
w = ...
functionTables.i w
```

We'd end up with something like this:
```
data FunctionTableClosure =
  ElementZero
  ElementOne Int
  ElementTwo (Int & Real)

y = 2
z = 3
functionTableClosures : Fin 3 => FunctionTableClosure = [ElementZero, ElementOne y, ElementTwo z]
i = ...
case functionTableClosures.i of
  ElementZero  -> w + w
  ElementOne y -> w + y
  ElementTwo z -> w * fst z
```

Note that we preserve work but not code size. A big drawback of this approach is that we can easily generate a lot of code and produce long compile times. We'll eventually need to have runtime functions to avoid this.

**Comment by duvenaud** [comment]
I'm going to leave a couple of examples here of related code that I'd like to work but doesn't currently:

This doesn't work:
```
disc' :(Fin 2)=>(Float->Float) = [\x:Float. 1.0, \x:Float. 2.0]
Compiler bug!
Please report this at github.com/google-research/dex-lang/issues

not implemented: (Float32 -> Float32)
CallStack (from HasCallStack):
  error, called at src/lib/Imp.hs:1002:8 in dex-0.1.0.0-Foy45KZj4WmEDjD4LlSjBZ:Imp
```

Making a table of functions inside a function works great:
```
def make_1d_discretization (n:Int) : (Fin n)=>(Float->Float) =
  edges = linspace (Post (Fin n)) 0.0 1.0
  for i. \x.
    if (x > edges.(left_post  i) &&
        x < edges.(right_post i)) then 1.0 else 0.0

disc = make_1d_discretization 4
```

But trying to manipulate those same functions fails:
```
def make_product_discretization {n d}
    (discs: d=>(n=>(Float->Float))) : (d=>n)=>((d=>Float)->Float) =
  for i. \x. prod for j:d. discs.j.(i.j) x.j

make_product_discretization [disc, disc]

Compiler bug!
Please report this at github.com/google-research/dex-lang/issues

not implemented: (Float32 -> Float32)
CallStack (from HasCallStack):
  error, called at src/lib/Imp.hs:1002:8 in dex-0.1.0.0-Foy45KZj4WmEDjD4LlSjBZ:Imp
```
