### ISSUE TITLE
rand only makes very small and strictly increasing numbers

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#25]
As far as I can tell `rand i` is a short-hand for: `i * 2.220446e-16`
This is not what I expected.

I expected `rand i` to generate random numbers between `0` and `1`.
I expected that   `i`  would act as a seed / state of the random number generator.
And for the correlation between  `i` and `rand i` not to be equal to `1`.

```
>=> for ii::10. rand(asint(ii))
[ 0.0
, 2.220446e-16
, 4.440892e-16
, 6.661338e-16
, 8.881784e-16
, 1.110223e-15
, 1.3322676e-15
, 1.5543122e-15
, 1.7763568e-15
, 1.9984014e-15 ]
>=> for ii::10. (real (asint ii))*2.220446e-16
[ 0.0
, 2.220446e-16
, 4.440892e-16
, 6.661338e-16
, 8.881784e-16
, 1.110223e-15
, 1.3322676e-15
, 1.5543122e-15
, 1.7763568e-15
, 1.9984014e-15 ]
```

**Comment by oxinabox** [comment]
I am thinking the way to get the behavior I want is
`rand (hash i 42)`

But I am AFK so can't check.
If so maybe `rand` would be better named `div2pow64` or something like that.

**Comment by dougalm** [comment]
Quite right. It's shorthand for `(i % 2^52) * 2^(-52)`, [defined here](https://github.com/google-research/dex-lang/blob/master/cbits/libdex.c#L117-L129). It maps a 64-bit word to the unit interval by using 52 of those bits as the mantissa of an IEEE 64-bit float. The intended use is to feed it pseudorandom bitstrings generated from the hash function. But it doesn't do the hashing itself! As you observe, you could create a function that behaves the way you're expecting by composing `rand` with the hash function:

    newKey :: Int -> Key
    newKey x = hash 0 x

    rand2 :: Int -> Real
    rand2 x = rand (newKey x)

    :p [for i::10. rand2 (asint i)]
    > [ [ 3.2959032e-4
    > , 0.9461821
    > , 0.95670474
    > , 0.15418614
    > , 0.9996959
    > , 0.6916184
    > , 0.80476636
    > , 0.96735865
    > , 0.44511434
    > , 1.4298539e-2 ] ]

    :p mean for i::10000. rand2 (asint i)
    > 0.50084704

The type of `rand` is `Key -> Real`, but `Key` is just an alias for `Int` so there's nothing stopping you calling `rand` with a raw int instead of hashing it first. The plan is to implement a newtype mechanism, and use it to make a `Key` type that's isomorphic to `Int` but distinct from it. Then `randn 0` won't typecheck, and you'll be forced to create a new key with something like the `newKey` above. With that check in place, there'd be no need for rand itself to do additional hashing, which would just be extra work. Until we have that, the `Key` types are just documentation. But we should at least include `newKey` in the prelude and the examples to suggest how it's intended to be used. I'll add that, but I'll keep this issue open until we have the newtype mechanism.

Seperately, even a newtype mechanism doesn't stop you from accidentally reusing they key. We're hoping to use the linear type system (since we already have one for AD purposes) to check that keys aren't reused.

Dex's PRNG system is modelled directly after [JAX's](https://github.com/google/jax/blob/master/design_notes/prng.md), which is based on a well established but shockingly underused idea from the functional programming community: the splittable PRNG. It's a good idea for many reasons, but it's especially helpful in a parallel setting. If you want to read more, [Splittable pseudorandom number generators using cryptographic hashing](http://publications.lib.chalmers.se/records/fulltext/183348/local_183348.pdf) describes the splitting model itself and [D.E. Shaw Research's counter-based PRNG](http://www.thesalmons.org/john/random123/papers/random123sc11.pdf) proposes the particular hash function we use.

**Comment by oxinabox** [comment]
Cool.   
Splittable PRNG's seems like a really good idea.  
Yes, I was surprised to findout recently just how much trouble people have generating independent random number  streams in parallel.

>  We're hoping to use the linear type system (since we already have one for AD purposes) to check that keys aren't reused.

Are there some notes on that somewhere that I can read?

**Comment by dougalm** [comment]
No, nothing written up yet. Hoping to get to that soon.
