### ISSUE TITLE
Compiler bug!Not an int

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#26]
I don't yet have a MWE for this,
and I don't know when I will next have time to work on it.

Here is a Gist that causes the error on the last `;p`
 - [code](https://gist.github.com/oxinabox/33f862cd5a89c6107432a0179e22ee6f#file-pso-dx)
 - [Error](https://gist.github.com/oxinabox/33f862cd5a89c6107432a0179e22ee6f#file-errorr-txt) (It has like 200 lines of "context")

The code has a bunch of extra type-asserts because I was debugging other mistakes of my own.

**Comment by dougalm** [comment]
Wow, this is a much longer program than anything I've written myself! Super cool. Thanks for the report. I'll take a look tomorrow. No MWE necessary.

**Comment by jyh1** [comment]
I actually saw similar errors a lot in the property testing. A MWE:

```
:p [0].([asidx 0].(asidx 0))
Compiler bug!Not an int: v_2.v_4
context:
v::Int[1]{
v[0] := %copy 0
v_2::Int[1]{
v_2[0] := %copy 0
v_4::Int[]{
v_4[] := %copy 0
%imptmp[] := %copy v.v_2.v_4}}}
```

Basically the code [there](https://github.com/google-research/dex-lang/blob/78d032cb573db855af81b54db4ba677afc6863e3/src/lib/Imp.hs#L243) assumes the nested `NGet` can only have the form `(a.i).j` instead of `a.(i.j)`. I guess no sane person would write code like this but it looks like some simplification rules would result in this weird form...

**Comment by dougalm** [comment]
Thanks, @jyh1, for tracking that down so quickly and coming up with the simple repro. The property testing is paying off already and we haven't even merged it yet! As you note, it's just that we're missing some cases in `checkInt`. I pushed a fix that just makes `checkInt` call `impExprType`, which should handle all the cases.

**Comment by oxinabox** [comment]
Awesome.

@dougalm would you like me to PR this code into `examples` assuming it is all working.

**Comment by dougalm** [comment]
Yes, happily!
