### ISSUE TITLE
Web and script numerical output differs from test rig expected output

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#263]
If you run the [ODE integrator example](https://github.com/google-research/dex-lang/blob/main/examples/ode-integrator.dx) in the web interface or the script interface you get different outputs than the test rig.

To be specific, running ```dex web examples/ode-integrator.dx``` or ```dex script  examples/ode-integrator.dx``` gives:

```
approx_e = odeint myDyn z0 t0 t1
:p approx_e
[[2.719482]]
```

But running ```make tests``` with these numbers as the expected output gives
```
approx_e = odeint myDyn z0 t0 t1			      (
:p approx_e						      (
> [[2.719482]]						      |	> [[2.7201762]]

.
.
.
make: *** [run-ode-integrator] Error 1
```

If I replace the expected output in the dex file with the expected answer from the tests, then the tests pass.  So in the current version of ode-integrator.dx, the expected results are what I got from the test suite, but I don't understand why they're different.

**Comment by apaszke** [comment]
Oh, ok. This is expected. Tests are executed with the `DEX_ALLOW_CONTRACTIONS=0`, to make them more stable across the virtual environments (some of which do not support FMA instructions). If your CPU does support them then Dex might take advantage of that, but it might change the numerical outputs. In theory they should only benefit you, because FMA doesn't round after the multiply.

Try running `export DEX_ALLOW_CONTRACTIONS=0` before running `dex` and the behavior you see should go away.

**Comment by duvenaud** [comment]
Ah, thanks for the explanation!  This might also explain why my outputs were slightly different than the Jax implementation.
