### ISSUE TITLE
modulo operation on negative number

### ISSUE THREAD

**Issue by jyh1** [google-research/dex-lang#32]
A result mismatch of JIT and interpreter from the prop tests:
```
:p mod 3 -2
3
```
The interpreter gives the correct result: -1.

The `urem` operation [here](https://github.com/google-research/dex-lang/blob/421214b79647de97254ec19098251c88910808fb/src/lib/JIT.hs#L437) should be changed to the signed version `srem`? However, [it's still not the modulo operator](https://llvm.org/docs/LangRef.html#id136). Maybe renaming the function to `rem` instead?

**Comment by dougalm** [comment]
Good catch. I agree. We should call it `rem` and lower it to LLVM's `srem`. Additionally, we actually do want a true modulo operator, for wrapping indices (including negative indices) to lie in `0 <= i < n`. But we can make one by using `rem` twice: `mod x y = rem (iadd y (rem x y)) y`. It's a quick fix so I'll just do it now rather than ask you to make a PR.
