### ISSUE TITLE
treat --o as a special case of -> ?

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#36]
Consider a function defined with `--o` like `neg`

```
>=> neg2:: Real->Real
... neg2 x = -1.0 * x

>=> map neg2 [1.0, 2.0]
[-1.0, -2.0]
>=> map neg [1.0, 2.0]
Compiler bug!
Please report this at github.com/google-research/dex-lang/issues

App: (Real -> Real) != (Real --o Real)
```

**Comment by oxinabox** [comment]
`asNonLin` is the work-around

```
>=> map (asNonLin neg) [1.0, 2.0]
[-1.0, -2.0]
```

**Comment by dougalm** [comment]
Good bug! And sorry for breaking you in b6d36d06e9.

As you point out, `a --o b` is a more restricted version of `a -> b`, so it should be possible to use an `a --o b` wherever you expect an `a -> b`. In other words, it seems like a subtype. But the situation with subtypes and Hindley-Milner type systems is a bit fraught. One problem, aiui, has to do with contravariance. While `a --o b` seems like a subtype of `a -> b`, if the type appears to the left of an arrow the situation is reversed. A function like `(a --o b) -> c` that only *accepts* an `a --o b` can't pretend to be an ordinary `(a -> b) -> c`. Linear transposition is an example.

A common strategy for situations like these is to use polymorphism instead of subtyping. There's a [very nice paper](https://arxiv.org/abs/1710.09756) on adding linear type systems to Haskell, which discusses the issue more (section 3.5). As well as polymorphism, they use a clever little bit of automatic eta expansion that lets even multiplicity-monomorphic linear functions behave as nonlinear ones (like inserting our `asNonLin` automatically). I imagine we could do something similar but I don't understand their scheme well enough yet.

I made a [prototype of linearity polymorphism](https://github.com/google-research/dex-lang/tree/linearity-experiments) (without the eta expansion) but I'm keeping it on a branch because it's too complex and ad-hoc. This whole linearity adventure is an experiment and I don't want to burden the type system too much until it's clear it's worth it. For now, I think we can put up with user-defined linear functions being a bit more awkward to write. In that spirit, I'm going to make the standard prelude functions like `fst` and `snd` nonlinear, with separate linear versions, `fstLin`, `sndLin` that you can use if you need them. We don't have huge Dex libraries, so I think we can afford the code duplication for now.

**Comment by oxinabox** [comment]
> A common strategy for situations like these is to use polymorphism instead of subtyping

I thought subtyping was a special case of polymorphism...


>  In that spirit, I'm going to make the standard prelude functions like fst and snd nonlinear, with separate linear versions, `fstLin`, `sndLin` that you can use if you need them.

I think this is OK. As mentioned yesterday, will also need a `mapLin` that is a 

```
mapLin :: (a -o b) -> n=>a -o n=>b
mapLin f xs = for i. f xs.i
```

maybe though `map`/`mapLin` just isn't worth having, given that `for` already has the desired behavour. That is interesting. It might be worth thinking more on that.
About higher order functions that are linear if and only if the the functions that are taking are linear.

---

On convention.
If we have `fstLin` and `sndLin`  for linear versions of functions.
That doesn't mesh well with `isum` and `imul` for integer versions of functions.

I wonder if somethin g like `fooBar_meta`  or something else might be a good convention for marking function that are just special versions of functions
`fst_lin`, `snd_lin`, `sum_int`, `mul_int`

**Comment by dougalm** [comment]
> About higher order functions that are linear if and only if the the functions that are taking are linear.

Right, this is exactly what linearity polymorphism would achieve. [In the multiplicity polymorphism branch](https://github.com/google-research/dex-lang/blob/linearity-experiments/prelude.dx#L129), 
map has type:

    map :: (a --* b) -> n=>a --* n=>b

Here `*` is a type variable (really a multiplicity variable) that can instantiated as either "linear" or "nonlinear".

**Comment by oxinabox** [comment]
will also such cases just be expressible as trivial `for`'s  ? i guess not,  but I can't think of any of the top of my head that are interesting

**Comment by oxinabox** [comment]
Is this resolved? Does `--o` even exist anymore?

**Comment by apaszke** [comment]
I think that it exists, but has atrophied enough that it's useless at this point. We don't even do linearity checking anymore.

**Comment by duvenaud** [comment]
Related:  It looks like Idris 2 had linearity subtyping for a while, but recently removed it because it make their typechecker unsound:

https://github.com/idris-lang/Idris2/pull/879
