### ISSUE TITLE
Slicing?

### ISSUE THREAD

**Issue by narfanar** [google-research/dex-lang#39]
Been trying to knot my way through getting something akin to slicing through filters and existentials.

But can't get past the need to create a range that's somehow convertible to an index set. Or put differently, a way to get an `E n` from a dynamic input `j`.

Attempts:

```hs
slice :: Int -> Int -> (E k. k=>(n=>Real -> Real))
slice i j =
rr = filter (lam k. and (ge k i) (lt k j)) iota @n -- No `ge` or `lt` :(((
for k. ki = rr.k; lam a. a.(asidx ki)
```

Should anything, besides the absence of comparators (`ge`, `lt`), make this not work?

**Comment by oxinabox** [comment]
Can you post an example input and (desired) output?

**Comment by narfanar** [comment]
Warning: This doesn't make much rigorous sense. Because I'm not sure what exactly I want the language to do.

```hs
sij = slice 2 10
-- :t sij === E k n. k=>((n=>Real) -> Real)
arr = iota @10
aij :: (t::k)=>Real -- Where does `t` even come from, here? Could it be inferrable from the body `sij arr`?
aij = for t. (sij arr)
-- aij should be [2, 3, ..., 9]
```

**Comment by dougalm** [comment]
I just added a `slice` function to the prelude. It takes the desired size as a type argument, and can fail (with a hard runtime error) if you're too close to the end of the array to get a valid slice of that size.

I think the version you're asking for is a bit different. You want to always get a slice, but you don't mind if it's smaller than you ask for (perhaps even empty) because you're near or past the ends of the array. Something like: `safeSlice :: Int -> Int -> n=>a -> (E k. k=>a)`

Unfortunately, to implement that function you need existential packing, which isn't implemented yet (our existentials are pretty underdeveloped generally). I'll ping this thread again when I add existential packing.
