### ISSUE TITLE
Allow trailing `,`

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#44]
It would be nice to allow trainling commas in tuples and vectors.
Because it means one can have a convention of always using them,
which gives a consistent look to multiline lists.
and then moving code becomes easier,

```
=> [1, 2,]

Parse error:179:1:
    |
179 | <empty line>
    | ^^^^^^^
unexpected "<newline>[1, 2,"
expecting decl or expr

=> (1, 2,)

Parse error:182:7:
    |
182 | (1, 2,)
    |       ^^
unexpected ")<newline><newline><newline><newline>"
expecting term
```

More realizstic example:
```
netParams = ( ..
    initAffine @2 @60 (newKey 10), ..
    initAffine @60 @60 (newKey 30), ..
    initAffine @60 @60 (newKey 30), ..
    initAffine @60 @60 (newKey 30), ..
    initAffine @60 @1 (newKey 20), ..
)
```

**Comment by dougalm** [comment]
The convention in Haskell is to put the comma at the start of the line, so you have

    x = 
      [ 1
      , 2
      , 3
      ]

But I don't think it would hurt to allow trailing commas too. Let's do it. It would also give you a way to write a singleton tuple `(1,)`. You don't need singleton tuples (Haskell doesn't have them, for example) since `(a,)` is isomorphic to `a`, but they might be quite useful if you're metaprogramming, generating Dex programs from another language.
