### ISSUE TITLE
Type error when function has both interface constraint and explicit type argument

### ISSUE THREAD

**Issue by RobertStanforth** [google-research/dex-lang#579]
With
```
instance [Add a, Add b] Add (a & b)
  add = \(a, b) (c, d). ( (a + c), (b + d))
  sub = \(a, b) (c, d). ( (a - c), (b - d))
  zero = (zero, zero)
```
The following fails:
```
def origin [Add ps0, Add ps1] (ps0:Type) -> (ps1:Type) -> : (ps0&ps1)
  = zero
```
It also fails with `?->` instead of `->`. However, the following works:
```
def origin [Add ps0, Add ps1] : (ps0&ps1)
  = zero
```

**Comment by apaszke** [comment]
While the error message is pretty bad, I would only say that I would expect `origin` to fail due to a scoping error (we restrict `ps0` to some type-class before we even take it as an argument). In the second case the implicitly polymorphic types always get prepended to the signature, so it doesn't suffer from the same issue.

**Comment by axch** [comment]
Status quo on main is that the error reports `ps0` as out of scope, thus:
```
def origin [Add ps0, Add ps1] (ps0:Type) (ps1:Type) : (ps0&ps1)
  = zero
> Error: variable not in scope: ps0
>
> def origin [Add ps0, Add ps1] (ps0:Type) (ps1:Type) : (ps0&ps1)
>                 ^^^
```

I think at this point, this error message is reasonable.  Moving the `ps0` and `ps1` arguments before the class constraints works just fine:
```
def origin (ps0:Type) (ps1:Type) [Add ps0, Add ps1] : (ps0&ps1)
  = zero

origin Nat Int
> (0, 0)
```
