### ISSUE TITLE
How to make comments on their own line

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#58]
In previous versions of Dex `.. -- comment` worked.
But it seems like `..` has stopped working in general lately.

### Attempt 1 (failed)
```
foo:: Real->Real
foo x = 
    .. -- Now we compute foo
    2.0 * x

Parse error:5:5:
  |
5 |     .. -- Now we compute foo
  |     ^^^^^
unexpected ".. --"
expecting decl or expr
foo 0.5
Error: variable not in scope: foo
```

### Attempt 2 (failed)
```
foo:: Real->Real
foo x = 
    -- Now we compute foo
    2.0 * x

Parse error:5:26:
  |
5 |     -- Now we compute foo
  |                          ^
unexpected "<newline>    "
expecting decl or expr
```

### Attempt 3 (works but kinda ugly?)
```
foo:: Real->Real
foo x = ( 
    -- Now we compute foo
    2.0 * x
)
```

**Comment by dougalm** [comment]
That's a bug. I'll push a fix soon. Since d714ab4ab84b5f ,the rule is supposed to be that you can have a cosmetic newlines whenever the newline can't be interpreted as ending a declaration. That includes when you have an opening paren that needs to be closed, but it should also apply immediately following a token like `=` which can't end a declaration.

d714ab4ab84b5f got rid of the `..` newline escaping mechanism. I was hoping we wouldn't need it any more. That might have been a mistake.

I'm not very satisfied with the treatment of newlines generally. I might open an issue to lay out the desiderata and see if we can find a better solution.
