### ISSUE TITLE
Effects with state need a Data constraint

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#609]
It looks like stateful updates of references to functions aren't supported.  Here's a MWE:
```
def updatefunc (f : (a->b)) : a->b =
  yieldState f \fref.
    fref := (get fref)

test_func : Float->Float = \x. sin x

:p updatefunc test_func
```
crashes with error:
```
not implemented: (Float32 -> Float32)
CallStack (from HasCallStack):
  error, called at src/lib/Imp.hs:662:8 in dex-0.1.0.0-3oYp3oqk0fKR5G5lrCUDc:Imp
```

I think I need this ability, since I want to be able to evaluate arbitrary partial derivatives when evaluating PDEs.  To do this I call `grad` in a `for` loop.

**Comment by apaszke** [comment]
Yeah that will be difficult to handle. All references have to be instances of `Data` (which we don't check at the moment, except for compiler crashes in our lowering) and functions are not. Calling grad in a loop is also not possible, because we have to perform AD during code generation, but this might require calling back into the compiler from the final binary. Is there no way to inline all of the `grad` calls into your program? If you know the bounds on the order you need you could make a tower of `if` statements that prepares the derivatives up to the threshold. I know it's a bit verbose, but this will be very hard to relax.

**Comment by duvenaud** [comment]
Thanks for explaining.

Yes, I can work around calling `grad` in a loop - I can just ask the user to provide a function that computes the gradients themselves. 
 This was just a way to provide a more generic / automatic interface.

**Comment by axch** [comment]
In effect, this has been refiled as #1150.
