### ISSUE TITLE
Problems using scan

### ISSUE THREAD

**Issue by martiningram** [google-research/dex-lang#622]
Hi Dex Team,

I've just started to play with this cool language and have run into a bit of a problem.

I would like to use `scan` (which I'm familiar with from JAX) but had some trouble, so I thought I'd try to write the simplest possible example:

```
to_sum = [1., 1., 1.]

def updateScan (cur_val: Float) (cur_carry: Float) : (Float & Float) =
    new_carry = cur_carry + cur_val
    (new_carry, 0.)

scan_init = 0.

:t scan scan_init updateScan
```
When I try to run this with `dex web` the output freezes and the terminal output states:
```
Not implemented Float32
CallStack (from HasCallStack):
  error, called at src/lib/Builder.hs:865:8 in dex-0.1.0.0-cplxjX7IqYJJeaxgDLDjq:Builder
```
At this point I have to restart `dex web` for anything to work again.

Is this expected behaviour? Am I running `scan` wrong somehow? Thanks for your help! :)

**Comment by dougalm** [comment]
Ooof, sorry, that's one of our notoriously bad error messages  (see #186). We should at least change [this line](https://github.com/google-research/dex-lang/blob/9873d1344578e963febf8c897a3877d37780472a/src/lib/Builder.hs#L865) to say something like "not an index set" instead of "not implemented".

The issue with your program is that Dex's scan has a slightly different signature to JAX's scan. You can see it in prelude.dx:

```
def scan (init:a) (body:n->a->(a&b)) : (a & n=>b) =
```
The body function takes an *index*, not an element. You can write a JAX-like scan like this:

```
def jaxy_scan (body: c -> a -> (c & b)) (init: c) (xs: n=>a) : (c & n=>b) =
  scan init \i carry. body carry xs.i

def updateScan (cur_val: Float) (cur_carry: Float) : (Float & Float) =
    new_carry = cur_carry + cur_val
    (new_carry, 0.)

to_sum = [1., 1., 1.]

scan_init = 0.

jaxy_scan updateScan scan_init to_sum
> (3., [0., 0., 0])
```

Of course, the hard crash you're seeing is our fault. We'd like you to see a (non-process-crashing!) type error along the lines of "Couldn't synthesize an index set for type Float". But we need to fix #186 to make that happen.

Separately, I always find scan an awkward combinator to use. I never know which arg is which. Scan in dex is just a user-defined function that uses the state effect internally. It's not a built-in combinator like it is in JAX. So I often prefer writing things using the state effect directly like this:

```
to_sum = [1., 1., 1.]
yieldState 0. \curSum.
  for i.
    curSum := get curSum + to_sum.i
> 3.0
```

**Comment by martiningram** [comment]
Hi Dougal,

Thank you very much for your comprehensive and helpful reply! That's great. I think I need to stare at type signatures a bit more to really get the hang of them, and this kind of example is really useful to help me learn.

I haven't played with your code just yet but I'm sure this will close the issue. Separately though, I expect that as I play more with Dex I'll run into some roadblocks due to my inexperience. Is there a good place somewhere to ask for help with Dex? The [Discussions](https://github.com/google-research/dex-lang/discussions) section? Sorry if this is obvious and I missed it :)

**Comment by codereport** [comment]
Just in case some else stumbles across this issue while trying to figure out how `scan` works, this is updated code from @dougalm's earlier post that compiles today (old code no longer works): 
```
def jaxy_scan(body: (c, a) -> (c, b), init: c, xs: n => a) -> (c, n => b) given (a|Data, b, c|Data, n|Ix) =
  scan init \i carry. body carry xs[i]

def update_scan(cur_val: Nat, cur_carry: Nat) -> (Nat, Nat) =
    new_carry = cur_carry + cur_val
    (new_carry, new_carry) -- made a small change here

to_sum = [1, 1, 1]

scan_init = 0

jaxy_scan update_scan scan_init to_sum
```

![image](https://github.com/google-research/dex-lang/assets/36027403/03fec120-74a9-47ac-8e97-81580122f83e)
