### ISSUE TITLE
Interfaces with more than one parameter.

### ISSUE THREAD

**Issue by sschoenholz** [google-research/dex-lang#701]
Hi! I'm thinking about how best to structure a bunch of different simulation environments that might share functionality. It feels like interfaces are the right way to do this, but please let me know if there's a better / more idiomatic way!

In any case, I'm currently thinking about something like this,
```
interface Simulation a b
  get_position : a -> b
  set_position : a -> b -> a
  get_velocity : a -> b
  set_velocity : a -> b -> a
  etc...

data FireDescentState n:Type dim: Type = MkFireDescentState {
     R:     (n=>dim=>Float) &
     V:     (n=>dim=>Float) &
     F:     (n=>dim=>Float) &
     dt:    Float        &
     alpha: Float        &
     n_pos: Int
}

instance Simulation (FireDescentState n dim) (n=>dim=>Float)
  get_position = \state. getAt #R state
  etc...

def velocity_verlet_step [Simulation a] (state: a) : a = ... 
```
However, this produces an ambiguous type error. I notice I don't see many examples of interfaces with more than one parameter. Is this a legal thing to do or should I be trying something else entirely? 
```
get_position state
Type error:Ambiguous type variables: [?1]

( 
lambda dicts: []
superclasses: []
instance dicts: []
[(_ans_, Let/lambda name _ans_4)]
, ( ( _ans_ @> <atom binder> ((b:Type)
                              ?-> (Simulation
                                     (FireDescentState (Fin 256) (Fin 2))
                                     b)
                              ?=> (FireDescentState (Fin 256) (Fin 2))
                              -> b) ((\a:Type b:Type ?->
                                        \d:(Simulation a b) ?=>
                                          ((\((MkSimulation (_, [x]))). x)
                                             d)) (FireDescentState
                                                    (Fin 256)
                                                    (Fin 2)))
_ans_1 @> <atom binder> ((Simulation (FireDescentState (Fin 256) (Fin 2)) ?1)
                         ?=> (FireDescentState (Fin 256) (Fin 2))
                         -> ?1) (_ans_ ?1)
_ans_2 @> <atom binder> ((FireDescentState (Fin 256) (Fin 2)) -> ?1) (_ans_1 _)
_ans_3 @> <atom binder> ?1 (_ans_2 state)
_ans_4 @> <atom binder> ?1 _ans_3

, lambda dicts: []
superclasses: []
instance dicts: [] )
, [ _ans_:((b:Type)
           ?-> (Simulation (FireDescentState (Fin 256) (Fin 2)) b)
           ?=> (FireDescentState (Fin 256) (Fin 2)) -> b) =
    (\a:Type b:Type ?->
       \d:(Simulation a b) ?=>
         ((\((MkSimulation (_, [x]))). x) d)) (FireDescentState
                                                 (Fin 256)
                                                 (Fin 2))
  , _ans_1:((Simulation (FireDescentState (Fin 256) (Fin 2)) ?1)
            ?=> (FireDescentState (Fin 256) (Fin 2)) -> ?1) = _ans_ ?1
  , _ans_2:((FireDescentState (Fin 256) (Fin 2)) -> ?1) = _ans_1 _
  , _ans_3:?1 = _ans_2 state
  , _ans_4:?1 = _ans_3 ] ) )
```

**Comment by apaszke** [comment]
Interfaces with multiple parameters are supported and should work (in Haskell world people usually call those multi-parameter type classes)!
```
interface HAddable a b  -- Heterogeneous add function
  hadd : a -> b -> a

instance HAddable Int64 Int32
  hadd = \x y. x + I32ToI64 y

hadd 2 3
> 5
```

However, as you've found yourself, in many cases it's easy to run into ambiguous situations with those, but it's a real failure not a compiler bug (though arguably that error message can be treated as a bug 😊). In particular, if there are parameters that only appear as types returned from class methods, you're likely to be in trouble. When you write
```
interface Simulation a b
  get_position : a -> b

instance Simulation (FireDescentState n dim) (n=>dim=>Float)
  get_position = \state. getAt #R state
```
then this in particular doesn't preclude you from adding an instance like this one later:
```
instance Simulation (FireDescentState n dim) AnyTypeCanGoHere
  get_position = ...
```
which means that any use of
```
get_position (MkFireDescentState ...)
```
is truly ambiguous, because the compiler has no idea that the `FireDescentState` will only ever have a single `b` type associated with it. In Haskell you could solve this using functional dependencies between interface parameters, but it's super heavyweight and we chose not to go down that path. Instead, our desired solution is to use _associated types_. Here's how this would look like:
```
interface Simulation sim
  Position sim : Type
  get_position : sim -> Position sim

instance Simulation (FireDescentState n dim)
  Position = n=>dim=>Float
  get_position = ...
```
note that in this case it is clear that for any simulation type `sim` there will always be a single `Position sim` type associated with it, which would make the use of `get_position` unambiguous.

However, while this is the _desired state_, our inference algorithm and type checker are still not fully equipped to be able to reason about associated types in all cases. The code as written above should already be accepted, but you might run into surprising type errors if you try writing functions that are polymorphic over simulation types. It's one of the next features I'm planning to work on, so we should get some support for it soon, but it's hard to give an estimate now.

**Comment by tscholak** [comment]
Hi, do the associated types have to be unique? that is, do I know what a is given an associated type b?
(In Haskell, one has the option of declaring a backwards functional dependency.)

**Comment by dougalm** [comment]
> do the associated types have to be unique? that is, do I know what a is given an associated type b?

No

> (In Haskell, one has the option of declaring a backwards functional dependency.)

Right, and we could try that path too. Another approach we're considering is to extend our family of function types to include functions that are known to be injective, which might let you do the same thing.

**Comment by tscholak** [comment]
Just noticed @apaszke discusses a related issue here https://github.com/google-research/dex-lang/issues/670#issue-1028974118

**Comment by apaszke** [comment]
Yup this is tracked in the other issue. I'll close this since I think there are no outstanding issues that are unique to this thread. Thanks everyone!
