### ISSUE TITLE
Syntax Change / Problem?

### ISSUE THREAD

**Issue by mmport80** [google-research/dex-lang#88]
I am trying out the tutorial.

Oddly, I see this in the REPL:

```
>=> f = lam z. x + z * y
Error: variable not in scope: lam
```

I'd appreciate any help.

**Comment by dougalm** [comment]
Oof, sorry. The tutorial is quite stale right now. For example, we switched to `\` instead of `lam`, but there have been many other changes too.

I disabled testing the tutorial because it printed out internal representations which changed too often. Without tests, it was inevitable that it would get stale. I'll update it, but in the meantime, there are examples in the `examples` directory [that are actually tested](https://github.com/google-research/dex-lang/blob/master/makefile#L48-L51) if you want to look at working code examples.

**Comment by mmport80** [comment]
Thanks Dougal! I prefer my lamba "\" also : )
